# conda version: 4.10.3, 4.11.0
name: nlp

channels:
  - pytorch

dependencies:
  - python=3.9
  - ipykernel=6.4.1
  - numpy=1.21.5
  - cupy=10.0.0
  - pandas=1.3.5
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - scikit-learn=1.0.1
  - scikit-learn-intelex
  - spacy=3.2.1
  - pytorch=1.10.1
  - cudatoolkit=11.3
  - pip=21.2.4
  - pip:
    - tensorflow==2.7.0